import {
    Button,
    ButtonGroup,
    message,
    Modal,
    Form,
    FormItem,
    InputPassword,
    Input,
    InputSearch,
    Card,
    Popconfirm,
    Collapse,
    CollapsePanel,
    Select,
    SelectOption,
    RadioButton,
    Radio,
    RadioGroup,
    Slider,
    Result,
    TypographyTitle,
    TypographyLink,
    Table,
    Tag,
    Tooltip,
    TabPane,
    Tabs,
    Layout,
    LayoutContent,
    LayoutHeader,
    LayoutSider,
    Popover,
    Avatar,
    Menu,
    MenuItem,
    SubMenu,
    Spin,
    Switch,
    Row,
    Col
} from "ant-design-vue";

export const Components = [
    Button,
    // ButtonGroup,
    Modal,
    Form,
    // FormItem,
    // InputPassword,
    Input,
    // InputSearch,
    Card,
    Popconfirm,
    Collapse,
    // CollapsePanel,
    Select,
    // SelectOption,
    // RadioButton,
    Radio,
    // RadioGroup,
    Slider,
    Result,
    // TypographyTitle,
    // TypographyLink,
    Table,
    Tag,
    Tooltip,
    // TabPane,
    Tabs,
    Layout,
    // LayoutContent,
    // LayoutHeader,
    // LayoutSider,
    Popover,
    Avatar,
    Menu,
    // MenuItem,
    // SubMenu,
    Spin,
    Switch,
    Row,
    Col
]